name: Publish and release
on:
  push:
    branches: [main]
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Install dependencies
        run: yarn

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build

      - name: Setup .npmrc file
        run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN

      - name: Run release command
        run: yarn release
